networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #I created network already using docker network create roboshop

services:
  mongodb:
    image: harshavardhan247/mongodb:v1
    container_name: mongodb
  catalogue: 
    image: harshavardhan247/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user: 
    image: harshavardhan247/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: harshavardhan247/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: harshavardhan247/:v1
    container_name: mysql
  shipping:
    image: harshavardhan247/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
